/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KubecaptainApiV1AppApp } from './KubecaptainApiV1AppApp';
import {
    KubecaptainApiV1AppAppFromJSON,
    KubecaptainApiV1AppAppFromJSONTyped,
    KubecaptainApiV1AppAppToJSON,
    KubecaptainApiV1AppAppToJSONTyped,
} from './KubecaptainApiV1AppApp';

/**
 * 
 * @export
 * @interface KubecaptainApiV1AppListResponse
 */
export interface KubecaptainApiV1AppListResponse {
    /**
     * 
     * @type {Array<KubecaptainApiV1AppApp>}
     * @memberof KubecaptainApiV1AppListResponse
     */
    items?: Array<KubecaptainApiV1AppApp>;
}

/**
 * Check if a given object implements the KubecaptainApiV1AppListResponse interface.
 */
export function instanceOfKubecaptainApiV1AppListResponse(value: object): value is KubecaptainApiV1AppListResponse {
    return true;
}

export function KubecaptainApiV1AppListResponseFromJSON(json: any): KubecaptainApiV1AppListResponse {
    return KubecaptainApiV1AppListResponseFromJSONTyped(json, false);
}

export function KubecaptainApiV1AppListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubecaptainApiV1AppListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(KubecaptainApiV1AppAppFromJSON)),
    };
}

export function KubecaptainApiV1AppListResponseToJSON(json: any): KubecaptainApiV1AppListResponse {
    return KubecaptainApiV1AppListResponseToJSONTyped(json, false);
}

export function KubecaptainApiV1AppListResponseToJSONTyped(value?: KubecaptainApiV1AppListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(KubecaptainApiV1AppAppToJSON)),
    };
}

