/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KubecaptainApiV1AppAppCISetting
 */
export interface KubecaptainApiV1AppAppCISetting {
    /**
     * 
     * @type {string}
     * @memberof KubecaptainApiV1AppAppCISetting
     */
    gitUrl: string;
    /**
     * 
     * @type {string}
     * @memberof KubecaptainApiV1AppAppCISetting
     */
    dockerfile: string;
}

/**
 * Check if a given object implements the KubecaptainApiV1AppAppCISetting interface.
 */
export function instanceOfKubecaptainApiV1AppAppCISetting(value: object): value is KubecaptainApiV1AppAppCISetting {
    if (!('gitUrl' in value) || value['gitUrl'] === undefined) return false;
    if (!('dockerfile' in value) || value['dockerfile'] === undefined) return false;
    return true;
}

export function KubecaptainApiV1AppAppCISettingFromJSON(json: any): KubecaptainApiV1AppAppCISetting {
    return KubecaptainApiV1AppAppCISettingFromJSONTyped(json, false);
}

export function KubecaptainApiV1AppAppCISettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubecaptainApiV1AppAppCISetting {
    if (json == null) {
        return json;
    }
    return {
        
        'gitUrl': json['gitUrl'],
        'dockerfile': json['dockerfile'],
    };
}

export function KubecaptainApiV1AppAppCISettingToJSON(json: any): KubecaptainApiV1AppAppCISetting {
    return KubecaptainApiV1AppAppCISettingToJSONTyped(json, false);
}

export function KubecaptainApiV1AppAppCISettingToJSONTyped(value?: KubecaptainApiV1AppAppCISetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gitUrl': value['gitUrl'],
        'dockerfile': value['dockerfile'],
    };
}

