/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KubecaptainApiV1AppCreateRequest
 */
export interface KubecaptainApiV1AppCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof KubecaptainApiV1AppCreateRequest
     */
    name: string;
}

/**
 * Check if a given object implements the KubecaptainApiV1AppCreateRequest interface.
 */
export function instanceOfKubecaptainApiV1AppCreateRequest(value: object): value is KubecaptainApiV1AppCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function KubecaptainApiV1AppCreateRequestFromJSON(json: any): KubecaptainApiV1AppCreateRequest {
    return KubecaptainApiV1AppCreateRequestFromJSONTyped(json, false);
}

export function KubecaptainApiV1AppCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubecaptainApiV1AppCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function KubecaptainApiV1AppCreateRequestToJSON(json: any): KubecaptainApiV1AppCreateRequest {
    return KubecaptainApiV1AppCreateRequestToJSONTyped(json, false);
}

export function KubecaptainApiV1AppCreateRequestToJSONTyped(value?: KubecaptainApiV1AppCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

