/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KubecaptainApiV1AppApp
 */
export interface KubecaptainApiV1AppApp {
    /**
     * 
     * @type {string}
     * @memberof KubecaptainApiV1AppApp
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof KubecaptainApiV1AppApp
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KubecaptainApiV1AppApp
     */
    users: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof KubecaptainApiV1AppApp
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the KubecaptainApiV1AppApp interface.
 */
export function instanceOfKubecaptainApiV1AppApp(value: object): value is KubecaptainApiV1AppApp {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function KubecaptainApiV1AppAppFromJSON(json: any): KubecaptainApiV1AppApp {
    return KubecaptainApiV1AppAppFromJSONTyped(json, false);
}

export function KubecaptainApiV1AppAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): KubecaptainApiV1AppApp {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'users': json['users'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function KubecaptainApiV1AppAppToJSON(json: any): KubecaptainApiV1AppApp {
    return KubecaptainApiV1AppAppToJSONTyped(json, false);
}

export function KubecaptainApiV1AppAppToJSONTyped(value?: Omit<KubecaptainApiV1AppApp, 'createdAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'users': value['users'],
    };
}

