// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kubecaptain/apis/internal/biz"
	"kubecaptain/apis/internal/conf"
	"kubecaptain/apis/internal/kube"
	"kubecaptain/apis/internal/kube/controller"
	"kubecaptain/apis/internal/server"
	"kubecaptain/apis/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	v, err := kube.NewKubeManager()
	if err != nil {
		return nil, nil, err
	}
	appUseCase, err := biz.NewAppUseCase(bootstrap, v)
	if err != nil {
		return nil, nil, err
	}
	appService := service.NewAppService(appUseCase)
	appCITaskUseCase, err := biz.NewAppCITaskUseCase(appUseCase, v)
	if err != nil {
		return nil, nil, err
	}
	appCITaskService := service.NewAppCITaskService(appCITaskUseCase)
	v2 := service.NewServices(appService, appCITaskService)
	grpcServer := server.NewGRPCServer(bootstrap, v2)
	httpServer := server.NewHTTPServer(bootstrap, v2)
	applicationReconciler := controller.NewApplicationReconciler(v)
	v3 := kube.NewManagedReconciler(applicationReconciler)
	kubeManagerServer, err := server.NewKubeManagerServer(bootstrap, v, v3)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, kubeManagerServer)
	return app, func() {
	}, nil
}
