// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kubecaptain/apis/internal/biz"
	"kubecaptain/apis/internal/conf"
	"kubecaptain/apis/internal/kube"
	"kubecaptain/apis/internal/kube/controller"
	"kubecaptain/apis/internal/server"
	"kubecaptain/apis/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	manager, err := kube.NewKubeManager()
	if err != nil {
		return nil, nil, err
	}
	client, err := kube.NewKubeClient(manager)
	if err != nil {
		return nil, nil, err
	}
	appUseCase, err := biz.NewAppUseCase(bootstrap, client)
	if err != nil {
		return nil, nil, err
	}
	appService := service.NewAppService(appUseCase)
	appCIUseCase, err := biz.NewAppCIUseCase(appUseCase, client)
	if err != nil {
		return nil, nil, err
	}
	appCIService := service.NewAppCIService(appCIUseCase)
	v := service.NewServices(appService, appCIService)
	grpcServer := server.NewGRPCServer(bootstrap, v)
	httpServer := server.NewHTTPServer(bootstrap, v)
	applicationReconciler := controller.NewApplicationReconciler(manager)
	v2 := kube.NewManagedReconciler(applicationReconciler)
	kubeManagerServer, err := server.NewKubeManagerServer(bootstrap, manager, v2)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, kubeManagerServer)
	return app, func() {
	}, nil
}
