// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kubecaptain/apis/internal/biz"
	"kubecaptain/apis/internal/conf"
	"kubecaptain/apis/internal/server"
	"kubecaptain/apis/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	appBiz := biz.NewAppBiz()
	appService := service.NewAppService(appBiz)
	v := service.NewServices(appService)
	grpcServer := server.NewGRPCServer(confServer, v)
	httpServer := server.NewHTTPServer(confServer, v)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
