/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  KubecaptainApiV1AppCreateRequest,
} from '../models/index';
import {
    KubecaptainApiV1AppCreateRequestFromJSON,
    KubecaptainApiV1AppCreateRequestToJSON,
} from '../models/index';

export interface AppCITaskServiceCreateRequest {
    name: string;
    kubecaptainApiV1AppCreateRequest: KubecaptainApiV1AppCreateRequest;
}

/**
 * 
 */
export class AppCITaskServiceApi extends runtime.BaseAPI {

    /**
     */
    async appCITaskServiceCreateRaw(requestParameters: AppCITaskServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling appCITaskServiceCreate().'
            );
        }

        if (requestParameters['kubecaptainApiV1AppCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'kubecaptainApiV1AppCreateRequest',
                'Required parameter "kubecaptainApiV1AppCreateRequest" was null or undefined when calling appCITaskServiceCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/app/{name}/ci/task`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KubecaptainApiV1AppCreateRequestToJSON(requestParameters['kubecaptainApiV1AppCreateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async appCITaskServiceCreate(requestParameters: AppCITaskServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.appCITaskServiceCreateRaw(requestParameters, initOverrides);
    }

}
